# Generated by Django 5.0.4 on 2024-04-30 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggy', '0002_alter_animal_type_fur_alter_animal_gender_delete_fur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='id',
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Female'), (2, 'Male')], default=None),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='doggy.health'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_fur',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Long Haired'), (2, 'Middle Haired'), (3, 'Short Haired')], default=None),
        ),
    ]
