# Generated by Django 5.0.4 on 2024-05-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggy', '0003_remove_animal_id_alter_animal_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name_shelter',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_building',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='animal',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='animal',
            name='life_story',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='health',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Healthy'), (2, 'Sick')], default=None),
        ),
    ]
